using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Thrivts.Domain.Entities;

namespace Thrivts.Infrastructure.Persistence.Configurations;

public class ProfileConfiguration : IEntityTypeConfiguration<Profile>
{
    public void Configure(EntityTypeBuilder<Profile> builder)
    {
        builder.ToTable("profiles");

        builder.HasKey(p => p.Id);

        builder.Property(p => p.Id)
            .ValueGeneratedNever(); // Id == auth.uid(), never generated by the DB.

        builder.Property(p => p.Role)
            .HasConversion<string>()
            .HasColumnName("role");

        builder.Property(p => p.Email).HasColumnName("email").IsRequired();
        builder.Property(p => p.FullName).HasColumnName("full_name").IsRequired();

        builder.Property(p => p.ApprovalStatus)
            .HasConversion<string>()
            .HasColumnName("approval_status");

        builder.Property(p => p.IsActive).HasColumnName("is_active");
    }
}
