using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Thrivts.Domain.Entities;
using Thrivts.Infrastructure.Persistence.Conversions;

namespace Thrivts.Infrastructure.Persistence.Configurations;

public class ProfileConfiguration : IEntityTypeConfiguration<Profile>
{
    public void Configure(EntityTypeBuilder<Profile> builder)
    {
        builder.ToTable("profiles");

        builder.HasKey(p => p.Id);

        builder.Property(p => p.Id)
            .ValueGeneratedNever(); // Id == auth.uid(), never generated by the DB.

        builder.Property(p => p.Role)
            .HasConversion(new SnakeCaseEnumConverter<Thrivts.Domain.Enums.UserRole>());

        builder.Property(p => p.LanguagePref)
            .HasConversion(new SnakeCaseEnumConverter<Thrivts.Domain.Enums.LanguagePref>());

        builder.Property(p => p.ApprovalStatus)
            .HasConversion(new SnakeCaseEnumConverter<Thrivts.Domain.Enums.ApprovalStatus>());

        builder.Property(p => p.Email).IsRequired();
        builder.Property(p => p.FullName).IsRequired();
    }
}
