using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Thrivts.Domain.Entities;

namespace Thrivts.Infrastructure.Persistence.Configurations;

public class ProfileConfiguration : IEntityTypeConfiguration<Profile>
{
    public void Configure(EntityTypeBuilder<Profile> builder)
    {
        builder.ToTable("profiles");

        builder.HasKey(p => p.Id);

        builder.Property(p => p.Id)
            .ValueGeneratedNever(); // Id == auth.uid(), never generated by the DB.

        // Role, LanguagePref, and ApprovalStatus map to their native Postgres enums via Npgsql's
        // own enum support — see NpgsqlEnumMapping.Configure.

        builder.Property(p => p.Email).IsRequired();
        builder.Property(p => p.FullName).IsRequired();

        // "WhatsApp" splits as "whats_app" under the snake_case naming convention, but the real
        // column is the single token "whatsapp" (it's a brand name, not two words).
        builder.Property(p => p.WhatsApp).HasColumnName("whatsapp");
    }
}
